#!/bin/bash

# get the sessionname for our current screen
screen -X sessionname
session=$(screen -X -Q lastmsg | awk '{print $NF'} | tr -d \')

# turn off the waiting after a msg is printed to screen
screen -x ${session} -X msgminwait 0
screen -x ${session} -X msgwait 0

let NEXT="0"

for win in $(screen -x ${session} -X -Q windows "%n "); do
  screen -x ${session} -p ${win} -X number ${NEXT}
  let NEXT="${NEXT}+1"
done

screen -x ${session} -X msgminwait 1
screen -x ${session} -X msgwait 5
